# Tahap 1: Build (Gunakan Maven dengan base JDK 25)
FROM maven:3.9-eclipse-temurin-25 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Tahap 2: Run (Gunakan Image JDK 25 yang ringan)
# Catatan: Jika versi alpine belum stabil untuk JDK 25, hapus "-alpine"
FROM eclipse-temurin:25-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]